# Generated by Django 4.2.1 on 2023-06-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Общая цена заказа')),
                ('products', models.ManyToManyField(to='market.product')),
            ],
            options={
                'verbose_name': 'Заказ',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Общая цена заказа')),
                ('products', models.ManyToManyField(to='market.product')),
            ],
            options={
                'verbose_name': 'Корзина',
            },
        ),
    ]
