# Generated by Django 4.2.1 on 2023-06-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_cart_buyer_order_buyer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
