# Generated by Django 4.2.1 on 2023-06-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_product_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=15, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
