# Generated by Django 4.2.1 on 2023-06-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_image',
            field=models.ImageField(blank=True, default='default_user.png', upload_to='images/', verbose_name='Фото игрока'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='default_prod.jpg', upload_to='images/', verbose_name='Изображение товара'),
        ),
    ]
