# Generated by Django 4.2.1 on 2023-06-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_player_player_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(auto_now_add=True, default='2023-08-06', verbose_name='Дата заказа'),
            preserve_default=False,
        ),
    ]
