# Generated by Django 4.2.1 on 2023-06-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_marketuser_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketUser',
        ),
    ]
